### ISSUE TITLE
Package provides a spurious `poetry` console script

### ISSUE THREAD

**Issue by neersighted** [coinmetrics/api-client-python#9]
While debugging a rather odd issue with a Poetry user, we discovered that your package is providing a spurious/nonsense console script that clobbers the user's Poetry install when present in the environment:

https://github.com/coinmetrics/api-client-python/blob/49168f602379e65d2ffb5936a7753f7492b45bf8/pyproject.toml#L34-L35

I'm guessing this was part of a bad copy-and-paste at some point -- I'd suggest removing it to avoid unexpectedly polluting the PATH of anything that uses your package.

**Comment by ianmclaughlin-cm** [comment]
Will remove this shortly, thank you for pointing this out.

**Comment by ianmclaughlin-cm** [comment]
This was resolved with previous merge

**Comment by neersighted** [comment]
It appears it's still present in the repository -- maybe you have unpushed commits somewhere?

https://github.com/coinmetrics/api-client-python/blob/55f9c980a906e6554b05bf36069b98df540ceaac/pyproject.toml#L34-L36
